db.pacientes.drop()
db.pacientes.insertMany([
    {
 nombrecompleto:{nombre:"Manuela",apellidos:"Perez Torroso"},
  edad:43,
  sexo:"mujer",
  embarazada:"si",
  estado:"medio",
  sangre:"B+",
  medico:"Rafael Alvarez",
  intervencionespendientes:true,
  vacunascovid:0,
  enfermedades:["colesterol,hipertension"],
  medicacion:["simvastatina,ramipril"],
  revision:new Date("2021-11-27")
 
},
{
  nombrecompleto:{nombre:"Mariangeles",apellidos:"Fernandez Suarez"},
   edad:23,
   sexo:"mujer",
   embarazada:"no",
   estado:"leve",
   sangre:"A+",
   medico:"Maria Esperanza",
   intervencionespendientes:false,
   vacunascovid:1,
   enfermedades:"mastoiditis",
   medicacion:"ceftriaxona",
   revision:new Date("2021-12-13")
  },
  {
    nombrecompleto:{nombre:"Roberto",apellidos:"Diaz Puentes"},
     edad:33,
     sexo:"hombre",
     embarazada:"si",
     estado:"sano",
     sangre:"B-",
     medico:"Rafael Alvarez",
     intervencionespendientes:true,
     vacunascovid:2,
     enfermedades:["asma,diabetes"],
     medicacion:["glimepirida,teofilina"],
     revision:new Date("2021-11-25")
   
   },
   {
    nombrecompleto:{nombre:"Manolo",apellidos:"Fuentes sierra"},
     edad:53,
     sexo:"hombre",
     estado:"grave",
     sangre:"0+",
     medico:"Manuel Romero",
     intervencionespendientes:true,
     vacunascovid:1,
     enfermedades:["cancer, epoc"],
     medicacion:["dactinomycin,albuterol"],
     revision:new Date("2022-01-07")
   
   },
   {
    nombrecompleto:{nombre:"Marina",apellidos:"Sanchez Garrido"},
     edad:35,
     sexo:"mujer",
     embarazada:"no",
     estado:"sano",
     sangre:"B-",
     medico:"Maria Esperanza",
     intervencionespendientes:false,
     vacunascovid:2,
     enfermedades:"parkinson",
     medicacion:"amantadina",
     revision:new Date("2022-01-07")
   },
   {
    nombrecompleto:{nombre:"Rocio",apellidos:"Sanchez Garrido"},
     edad:35,
     sexo:"mujer",
     embarazada:"si",
     estado:"grave",
     sangre:"B-",
     medico:"Maria Esperanza",
     intervencionespendientes:false,
     vacunascovid:0,
     enfermedades:["bronquitis,influenza"],
     medicacion:["analgesicos,zanamivir"],
     revision:new Date("2022-01-03")
   },
   {
    nombrecompleto:{nombre:"Maria",apellidos:"Sanchez Garrido"},
     edad:36,
     sexo:"mujer",
     embarazada:"no",
     estado:"leve",
     sangre:"B-",
     medico:"Maria Esperanza",
     intervencionespendientes:false,
     vacunascovid:1,
     enfermedades:"hipertension",
     medicacion:"ramipril",
     revision:new Date("2022-01-03")
   },
   {
    nombrecompleto:{nombre:"Pepe",apellidos:"Castillos Sanchez"},
     edad:45,
     sexo:"hombre",
     estado:"medio",
     sangre:"a-",
     medico:"Manuel Romero",
     intervencionespendientes:true,
     vacunascovid:1,
     enfermedades:["hipertension,gota"],
     medicacion:["ramipril,colquicina"],
     revision:new Date("2022-02-20")
   },
   {
    nombrecompleto:{nombre:"Jose",apellidos:"Romero Diaz"},
     edad:15,
     sexo:"hombre",
     estado:"sano",
     sangre:"b-",
     medico:"Rafael Alvarez",
     intervencionespendientes:false,
     vacunascovid:1,
     enfermedades:"no",
     medicacion:"no",
     revision:new Date("2022-02-30")
   },
   {
    nombrecompleto:{nombre:"Jose",apellidos:"Romero Diaz"},
     edad:49,
     sexo:"hombre",
     estado:"grave",
     sangre:"b-",
     medico:"Rafael Alvarez",
     intervencionespendientes:false,
     vacunascovid:2,
     enfermedades:"cancer,colesterol",
     medicacion:"dactinomycin",
     revision:new Date("2021-12-15")
   },
   {
    nombrecompleto:{nombre:"Macarena",apellidos:"Diaz Guerra"},
     edad:44,
     sexo:"mujer",
     embarazada:"no",
     estado:"grave",
     sangre:"0-",
     medico:"Maria Esperanza",
     intervencionespendientes:false,
     vacunascovid:2,
     enfermedades:"hipertension",
     medicacion:"ramipril",
     revision:new Date("2021-12-01")
   },
   {
    nombrecompleto:{nombre:"Mohammed",apellidos:"Fateh"},
     edad:57,
     sexo:"hombre",
     estado:"leve",
     sangre:"0+",
     medico:"Esperanza Pacheco",
     intervencionespendientes:true,
     vacunascovid:1,
     enfermedades:"no",
     medicacion:"no",
     revision:new Date("2021-12-30")
   },
   {
    nombrecompleto:{nombre:"Mario",apellidos:"Marquez Rios"},
     edad:81,
     sexo:"hombre",
     estado:"medio",
     sangre:"a+",
     medico:"Esperanza Pacheco",
     intervencionespendientes:false,
     vacunascovid:0,
     enfermedades:"mastoiditis",
     medicacion:"ceftriaxona",
     revision:new Date("2022-01-30")
   },
   {
    nombrecompleto:{nombre:"Maria",apellidos:"Cazallo Aragon"},
     edad:83,
     sexo:"mujer",
     embarazada:"no",
     estado:"medio",
     sangre:"a+",
     medico:"Rafael Alvarez",
     intervencionespendientes:true,
     vacunascovid:2,
     enfermedades:["colesterol,diabetes"],
     medicacion:["glimepirida,simvastatina"],
     revision:new Date("2022-03-15")
   },
   {
    nombrecompleto:{nombre:"Godofredo",apellidos:"Campos Villalba"},
     edad:63,
     sexo:"hombre",
     estado:"grave",
     sangre:"a+",
     medico:"Esperanza Pacheco",
     intervencionespendientes:true,
     vacunascovid:0,
     enfermedades:["colesterol,diabetes,cancer"],
     medicacion:["glimepirida,simvastatina,dactinomycin"],
     revision:new Date("2022-01-15")
   },
   {
    nombrecompleto:{nombre:"Juan",apellidos:"Perez Rico"},
     edad:24,
     sexo:"hombre",
     estado:"leve",
     sangre:"0-",
     medico:"Esperanza Pacheco",
     intervencionespendientes:false,
     vacunascovid:1,
     enfermedades:"bronquitis",
     medicacion:"analgesicos",
     revision:new Date("2021-12-01")
   },
   {
    nombrecompleto:{nombre:"Claudia",apellidos:"Bejarano Saguar"},
     edad:19,
     sexo:"mujer",
     embarazada:"si",
     estado:"sano",
     sangre:"b+",
     medico:"Manuel Romero",
     intervencionespendientes:false,
     vacunascovid:2,
     enfermedades:"asma",
     medicacion:"teofilina",
     revision:new Date("2021-11-21")
   },
   {
    nombrecompleto:{nombre:"Antonio",apellidos:"Santos Lobata"},
     edad:37,
     sexo:"hombre",
     estado:"medio",
     sangre:"b-",
     medico:"Rafael Alvarez",
     intervencionespendientes:false,
     vacunascovid:2,
     enfermedades:["cancer,epoc"],
     medicacion:["dactinomycin,albuterol"],
     revision:new Date("2021-11-16")
   },
   {
    nombrecompleto:{nombre:"Marta",apellidos:"Rodriguez Navarro"},
     edad:27,
     sexo:"mujer",
     embarazada:"no",
     estado:"leve",
     sangre:"a-",
     medico:"Maria Esperanza",
     intervencionespendientes:false,
     vacunascovid:1,
     enfermedades:"epoc",
     medicacion:"albuterol",
     revision:new Date("2021-12-19")
   },
   {
    nombrecompleto:{nombre:"Lorena",apellidos:"Serrano"},
     edad:18,
     sexo:"mujer",
     embarazada:"no",
     estado:"grave",
     sangre:"b+",
     medico:"Manuel Romero",
     intervencionespendientes:true,
     vacunascovid:2,
     enfermedades:["bronquitis,influenza,gota"],
     medicacion:["analgesicos,zanamivir,colquicina"],
     revision:new Date("2021-11-16")
   }])
